src/main/resources/mybatis/mybatis-config.xml
config: mybatis-config.xml 폼 셋팅
please check.....
=> config: mybatis-config.xml 폼 셋팅

src/main/java/com/universestay/project/docs/SwaggerConfig.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- 연관된 이슈 : task-91
https://github.com/GeumZzoks/universeStay/pull/2 에서 분기된 에러임.
- 흑흑
=> task-195 / fix: swagger & datasource bean 생성 충돌 에러 해결

src/main/java/com/universestay/project/user/controller/UserWithdrawalController.java, src/main/java/com/universestay/project/user/dao/UserWithdrawalDao.java, src/main/java/com/universestay/project/user/dao/UserWithdrawalDaoImpl.java, src/main/java/com/universestay/project/user/dto/UserDto.java, src/main/java/com/universestay/project/user/service/UserWithdrawalService.java, src/main/java/com/universestay/project/user/service/UserWithdrawalServiceImpl.java, src/main/resources/mybatis/mapper/user/userWithdrawalMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
- 회원탈퇴 api 개발
- 프로젝트 디렉토리 구조 변경
- root-context.xml 설정 변경
=> feat: 회원탈퇴 api 개발, structure: 프로젝트 디렉토리 구조변경

src/main/java/com/universestay/project/admin/controller/EventController.java
오류 발생으로 EventController 내용 주석처리 및 경로 통일
=> fix: 관리자 이벤트 페이지 Controller 주석처리

src/main/java/com/universestay/project/dto/AddressDto.java, src/main/java/com/universestay/project/dto/CommonStatusDto.java, src/main/java/com/universestay/project/dto/RoomAmenityDto.java, src/main/java/com/universestay/project/dto/RoomDto.java, src/main/java/com/universestay/project/dto/RoomImgDto.java, src/main/java/com/universestay/project/dto/RoomViewDto.java, src/main/java/com/universestay/project/dto/ViewDto.java
- 주소, 상태코드, 숙소, 숙소 편의시설, 숙소 이미지, 숙소전망, 전망 DTO 추가 
(@ApiModelProperty 속성은 notes, example, required 만 적용)
- 연관된 이슈 : http://localhost:8080/swagger-ui.html 들어가서 Models에 DTO 가 적용이 안됨
=> feat: 주소, 상태코드, 숙소, 숙소 편의시설, 숙소 이미지, 숙소전망, 전망 DTO 추가

src/main/java/com/universestay/project/user/dto/CardDto.java, src/main/java/com/universestay/project/user/dto/CouponDto.java, src/main/java/com/universestay/project/user/dto/OAuthDto.java, src/main/java/com/universestay/project/user/dto/ProfileImgDto.java, src/main/java/com/universestay/project/user/dto/RoomReviewDto.java, src/main/java/com/universestay/project/user/dto/UserCouponDto.java, src/main/java/com/universestay/project/user/dto/UserDto.java
=> feat: OAuth, 프로필이미지, 결제카드, 쿠폰, 룸리뷰, 유저쿠폰, 유저 Dto 추가

src/main/java/com/universestay/project/docs/SwaggerConfig.java, src/main/java/com/universestay/project/dto/AlertDto.java, src/main/java/com/universestay/project/dto/AlertRuleDto.java, src/main/java/com/universestay/project/dto/BookingDto.java, src/main/java/com/universestay/project/dto/PaymentDto.java, src/main/java/com/universestay/project/dto/RefundDto.java
=> feat: Alert, AlertRule, Booking, Payment, Refund Dto 추가

src/main/java/com/universestay/project/dto/LikeDto.java, src/main/java/com/universestay/project/user/dto/UserDto.java
- ERD 설계에 따른 DTO 생성(entity)
- LikeDto 추가
- UserDto 수정
- user_id2에 @ApiModelProperty(example = "0ca24692-89ea-11ee-b9d1-0242ac120002") -> (example = "ae405ce0-8a9b-11ee-b9d8-0242ac120002”) 변경
=> feat: LikeDto 추가 / UserDto 수정

src/main/webapp/join.jsp, src/main/webapp/resources/css/user/join.css, src/main/webapp/resources/js/join.js
=> feat: 회원가입 html, css, js

src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/java/com/universestay/project/user/controller/UserWithdrawalController.java, src/main/java/com/universestay/project/user/dao/UserLoginDao.java, src/main/java/com/universestay/project/user/dao/UserLoginDaoImpl.java, src/main/java/com/universestay/project/user/dao/UserWithdrawalDao.java, src/main/java/com/universestay/project/user/service/UserLoginService.java, src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java, src/main/resources/mybatis/mapper/user/userLoginMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/views/user/loginForm.jsp
=> feat: 로그인 API 개발

src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/java/com/universestay/project/user/service/UserLoginService.java, src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java, src/main/java/com/universestay/project/viewTest.java, src/main/webapp/WEB-INF/views/user/loginForm.jsp
=> feat: 로그인 뷰 에러처리

src/main/java/com/universestay/project/admin/controller/LoginController.java, src/main/java/com/universestay/project/admin/dao/LoginAdminDao.java, src/main/java/com/universestay/project/admin/dao/LoginAdminDaoImpl.java, src/main/java/com/universestay/project/admin/dto/AdminDto.java, src/main/java/com/universestay/project/admin/service/LoginAdminService.java, src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java, src/main/java/com/universestay/project/docs/SwaggerConfig.java, src/main/java/com/universestay/project/filter/AdminFilter.java, src/main/resources/mybatis/mapper/admin/loginMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/views/admin/dashboard.jsp, src/main/webapp/WEB-INF/views/admin/loginForm.jsp, src/main/webapp/resources/css/admin/loginForm.css
- (main) 관리자 계정 API 로그인 구현 파일 목록
- 파일 정리
- 디자인(css) 수정
- Comment 추가(Swagger TODO)
- 관리자 계정 API 로그인 구현 파일 목록
```
src/main/java/com/universestay/project/admin/controller/LoginController.java
src/main/java/com/universestay/project/admin/dao/LoginAdminDao.java
src/main/java/com/universestay/project/admin/dao/LoginAdminDaoImpl.java
src/main/java/com/universestay/project/admin/dto/AdminDto.java
src/main/java/com/universestay/project/admin/service/LoginAdminService.java
src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java
src/main/java/com/universestay/project/filter/AdminFilter.java
src/main/resources/mybatis/mapper/admin/loginMapper.xml
src/main/resources/mybatis/mybatis-config.xml
src/main/webapp/WEB-INF/views/admin/dashboard.jsp
```
- remove: 파일 정리(empty.txt)
``` …
```
=> feat: [1차 개발] 관리자 계정 API 로그인 구현

src/main/webapp/WEB-INF/views/common/admin/footer.jsp, src/main/webapp/WEB-INF/views/common/admin/header.jsp, src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
- 관리자 페이지 header, navigation, footer 에 global.css 적용, 세부 css 수정
- 각 jsp에 <link href="/resources/css/common/global.css" rel="stylesheet"/> 추가
- header
- navigation
-footer
- 관리자 페이지 화면 구성할때 상단 이미지와 다르면 말씀해주시면 감사하겠습니다.
=> Task 244 : 관리자 페이지 header, navigation, footer 에 global.css 적용 및 css 수정

src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/webapp/WEB-INF/views/admin/event.jsp, src/main/webapp/WEB-INF/views/admin/eventInput.jsp, src/main/webapp/WEB-INF/views/admin/eventList.jsp, src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp, src/main/webapp/WEB-INF/views/common/admin/footer.jsp, src/main/webapp/WEB-INF/views/common/admin/header.jsp, src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
- 관리자 이벤트 페이지 jsp API 수정
- 관리자 이벤트 컨트롤러 API 수정 ("/event" -> "/admin/event")
- 관리자 이벤트 컨트롤러 주석 추가
- 관리자 이벤트 컨트롤러 예외처리 추가
- logback 사용법을 잘 모르겠어서 일단 e.printStacTrace(); 로 예외처리 했습니다
=> Task 254 관리자 이벤트 페이지 컨트롤러 수정 / 주석추가 & 예외처리

src/main/webapp/WEB-INF/views/admin/loginForm.jsp, src/main/webapp/resources/css2/screens/admin/loginForm.css
- CSS 파일 경로 수정 및 BEM 명명규칙 적용
- 관리자 계정 로그인 HTML & CSS
```
src/main/webapp/WEB-INF/views/admin/loginForm.jsp
src/main/webapp/resources/css2/screens/admin/loginForm.css
```
=> refactor: CSS 파일 경로 수정 및 BEM 명명규칙 적용

src/main/webapp/WEB-INF/views/admin/event.jsp, src/main/webapp/WEB-INF/views/admin/eventInput.jsp, src/main/webapp/WEB-INF/views/admin/eventList.jsp, src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp, src/main/webapp/resources/css/admin/event.css
- 관리자 이벤트 페이지 css & jsp 수정
- 형식 꺠지지 않게 수정했습니다
- 파일 경로는 아직 수정되지 않았습니다
=> Task 255 : 이벤트 페이지 CSS & JSP 파일 CSS 변경

src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/java/com/universestay/project/user/controller/UserLogoutController.java, src/main/java/com/universestay/project/user/dao/UserLoginDao.java, src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java, src/main/webapp/WEB-INF/views/HI.jsp, src/main/webapp/WEB-INF/views/user/loginForm.jsp, src/test/java/com/universestay/project/user/dao/UserLoginDaoImplTest.java
- UserLogoutController 추가 
- UserLoginController Mapping 수정
- UserLoginDao 테스트 코드 추가
- UserLogoutController 추가 
- UserLoginController Mapping 수정
- loginForm 수정
- UserLoginDao 테스트 코드 추가
=> feat: 로그아웃 컨트롤러 추가, 로그인 컨트롤러 맵핑 수정

src/main/java/com/universestay/project/admin/controller/LoginController.java, src/main/java/com/universestay/project/admin/controller/RegisterController.java, src/main/java/com/universestay/project/admin/dao/LoginAdminDao.java, src/main/java/com/universestay/project/admin/dao/LoginAdminDaoImpl.java, src/main/java/com/universestay/project/admin/dao/RegisterDao.java, src/main/java/com/universestay/project/admin/dao/RegisterDaoImpl.java, src/main/java/com/universestay/project/admin/service/LoginAdminService.java, src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/loginMapper.xml, src/main/resources/mybatis/mapper/admin/registerMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/test/java/com/universestay/project/admin/dao/RegisterDaoImplTest.java
- 관리자 회원가입 API 작성
- Dao 구현
- MyBatis - Mapper 구현
- Test 코드 작성
```
src/main/java/com/universestay/project/admin/controller/RegisterController.java
src/main/java/com/universestay/project/admin/dao/RegisterDao.java
src/main/java/com/universestay/project/admin/dao/RegisterDaoImpl.java
src/main/resources/mybatis/mapper/admin/registerMapper.xml
```
```
src/test/java/com/universestay/project/admin/dao/RegisterDaoImplTest.java
```
=> test: Dao, Mapper 구현, Test 코드 작성 및 테스트

src/main/java/com/universestay/project/common/exception/CommonException.java, src/main/java/com/universestay/project/common/exception/StatusCode.java
- ClassNotFoundException 에러 처리
- CommonException, StatusCode 클래스 추가
=> fix: ClassNotFoundException 에러 처리

src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/java/com/universestay/project/admin/dao/EventDao.java, src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java, src/main/java/com/universestay/project/admin/service/EventService.java, src/main/java/com/universestay/project/admin/service/EventServiceImpl.java, src/main/resources/mybatis/mapper/admin/EventMapper.xml, src/main/webapp/WEB-INF/views/admin/event.jsp, src/main/webapp/WEB-INF/views/admin/eventInput.jsp, src/main/webapp/WEB-INF/views/admin/eventList.jsp, src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp, src/main/webapp/resources/css/admin/event.css
- 관리자 이벤트 페이지 조회수 기능 추가(EventMapper & EventService & EventServiceImpl & EventController 수정)
- EventController 내부의 EventDao -> 전부 EventService로 변경
- EventService & EventServiceImpl 수정
- 세부 css 변경
- EventController 내 주석 추가
=> Task 275 : 관리자 이벤트 페이지 조회수 기능 추가 / 이벤트 컨트롤러(Dao -> Service)로 수정 / 이벤트 목록 세부 css 변경

src/main/webapp/WEB-INF/views/user/withdrawal.jsp, src/main/webapp/resources/css2/screens/user/withdrawal.css, src/main/webapp/resources/css2/style.css
- user/withdrawal.jsp css BEM 명명 변경
=> refactor: css 폴더 구조에 따른 BEM 명명 변경

src/main/webapp/resources/css2/style.css
- style.css 주석처리 해제
- style.css 주석처리 해제
=> comment: style.css 주석처리 해제

src/main/webapp/WEB-INF/views/user/loginForm.jsp
- user/loginForm 수정 oauth button에 onclick 속성 추가
=> fix: user/loginForm 수정 oauth button에 onclick 속성 추가

src/main/java/com/universestay/project/user/controller/UserLogoutController.java, src/main/webapp/WEB-INF/views/common/user/header.jsp
- 로그아웃 컨트롤러 반환 리다이렉트 확장자 수정
- 로그아웃 버튼 눌렀을때 onclick 이벤트 추가
=> fix: 로그아웃 컨트롤러 반환 리다이렉트 확장자 수정, 로그아웃 버튼 눌렀을때 onclick이벤트 추가

src/main/java/com/universestay/project/admin/controller/LoginController.java, src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java, src/main/java/com/universestay/project/common/Uuid.java, src/main/java/com/universestay/project/common/exception/CommonException.java, src/main/java/com/universestay/project/common/exception/StatusCode.java, src/main/java/com/universestay/project/filter/AdminFilter.java
- 커스터마이징 UUID 생성
- 관리자 로그인 API 보완
- [2차 개발] 관리자 로그인 API 보완
```
src/main/java/com/universestay/project/admin/controller/LoginController.java
src/main/java/com/universestay/project/admin/service/LoginAdminServiceImpl.java
src/main/java/com/universestay/project/filter/AdminFilter.java
```
- CUSTOM UUID 생성
```
src/main/java/com/universestay/project/common/Uuid.java
```
=> refactor: [2차 개발] 관리자 로그인 API 보완

src/main/java/com/universestay/project/filter/UserFilter.java
- 유저 접근권한 제한하는 웹필터 생성
- user webfilter 생성 
@nickhealthy 감사합니다 냠냠굿^^
=> feat: user webfilter 추가 ( 추후 urlPatterns 수정 필요)

src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/java/com/universestay/project/admin/service/EventServiceImpl.java, src/main/webapp/WEB-INF/views/admin/event.jsp, src/main/webapp/WEB-INF/views/admin/eventInput.jsp, src/main/webapp/WEB-INF/views/admin/eventList.jsp, src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp, src/main/webapp/WEB-INF/views/common/admin/footer.jsp, src/main/webapp/WEB-INF/views/common/admin/header.jsp, src/main/webapp/WEB-INF/views/common/admin/navigation.jsp, src/main/webapp/resources/css/admin/event.css, src/main/webapp/resources/css2/components/admin/footer.css, src/main/webapp/resources/css2/components/admin/header.css, src/main/webapp/resources/css2/components/admin/navigation.css, src/main/webapp/resources/css2/screens/admin/event.css
- 이벤트 페이지 CSS BEM 변경(경로 추가)
- header, navigation, footer CSS BEM & CSS 경로 변경
- 이벤트 서비스, 컨트롤러 변경
- @AutoWired HttpSession session 제거 / Controller 매개변수로 추가) -> 테스트 에러 안납니다(@jinkwon9301 감사합니다)
=> refactor: 이벤트 페이지 CSS BEM / CSS 수정 / 이벤트 서비스, 컨트롤러 변경

src/main/java/com/universestay/project/admin/dto/CouponDto.java
- CouponDto 클래스 - 관리자 dto 폴더로 이동
=> rename: CouponDto 클래스 - 관리자 dto 폴더로 이동

src/main/java/com/universestay/project/admin/dto/InquiryDto.java, src/main/webapp/resources/css2/style.css
- fix: InquriyDto 경로 문제로 인한 톰캣 구동 에러 해결
- fix: style.css 주석 풀어서 css 적용
=> fix: InquriyDto 경로 문제로 인한 톰캣 구동 에러 해결

src/main/java/com/universestay/project/admin/controller/DashBoardController.java, src/main/java/com/universestay/project/admin/dao/DashBoardDao.java, src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java, src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml, src/main/webapp/WEB-INF/views/admin/dashboard.jsp
- 관리자 대시보드 API & VIEW 1차 개발 구현
@m11ng 
예림찌도 제꺼 맡아주셨으니(관리자 - 대시보드) reviewer 에 걸어둘게요! 작업하시기 전에 pull 받고 함 확인해보시면 될 것 같아여
HTML & CSS 도 조금 작업해놨는데 참고해서 HTML/CSS 작업하시면 될 거 같고, 
JSP로 forEach 같은 태그 달아서 프로그래밍 해주셔도 좋슴돠
- 작업 파일 목록
```
src/main/java/com/universestay/project/admin/controller/DashBoardController.java
src/main/java/com/universestay/project/admin/dao/DashBoardDao.java
src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java
src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml
src/main/webapp/WEB-INF/views/admin/dashboard.jsp
```
=> feat: [1차 개발] 관리자 - 대시보드 API & VIEW

src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java
tomcat 기동 버그 수정 - DashBoardDaoImpl
DashBoardDaoImpl.java 수정
=> !HOTFIX: tomcat 기동 버그 수정 - DashBoardDaoImpl

src/main/java/com/universestay/project/admin/controller/UserManagementController.java, src/main/java/com/universestay/project/admin/dao/UserManagementDao.java, src/main/java/com/universestay/project/admin/dao/UserManagementDaoImpl.java, src/main/java/com/universestay/project/admin/service/UserManagementService.java, src/main/java/com/universestay/project/admin/service/UserManagementServiceImpl.java, src/main/java/com/universestay/project/common/PageHandler.java, src/main/java/com/universestay/project/common/SearchCondition.java, src/main/java/com/universestay/project/filter/AdminFilter.java, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/views/admin/userInfo.jsp, src/main/webapp/WEB-INF/views/admin/userList.jsp, src/test/java/com/universestay/project/admin/dao/UserManagementDaoImplTest.java
Rename: PageHandler, SearchCondition 파일 디렉토리 이동
(admin.dto -> common)
Feat: UserManagementController - URL Mapping 수정 
admin/userlist -> admin/user/list
admin/userinfo -> admin/user/info
Feat: AdminFilter - whiteList 추가
- whiteList에 추가된 url은 필터 안걸림
=> task-115 Rename, Feat

src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/java/com/universestay/project/admin/dao/EventDao.java, src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java, src/main/java/com/universestay/project/admin/service/EventService.java, src/main/java/com/universestay/project/admin/service/EventServiceImpl.java
관리자 이벤트 페이지 내 SearchCondition & PageHandler 경로 수정
=> refactor : 관리자 이벤트 페이지 SearchCondition & PageHandler 경로 수정

src/main/java/com/universestay/project/user/service/JoinServiceImpl.java, src/main/webapp/resources/js/join.js
=> Task 303 - 회원가입 API 

src/main/java/com/universestay/project/user/dto/ProfileImgDto.java, src/main/java/com/universestay/project/user/dto/UserDto.java, src/main/resources/mybatis/mapper/user/userInfoMapper.xml
-  
- UserDto 수정 (profile_img_url / profile_img_id 삭제)
- userInfoMapper.xml 변경
=> Task 304 : UserDto 변경

src/main/webapp/WEB-INF/views/admin/register.jsp, src/main/webapp/resources/css2/screens/admin/register.css, src/main/webapp/resources/css2/style.css, src/main/webapp/resources/js/admin/register.js
- [관리자] 회원가입 등록 폼 HTML & CSS & JS
- @beautiflow 님께 무한감사..👍
- CSS 파일은 별도로 분리해서 나누었고, 명명규칙도 그에 맞게 HTML, CSS, JS 모두 수정하였습니다!
- **일단 이대로 올려두고 나중에 회원가입 폼을 변경할 시간 있으면 관리자용으로 따로 해볼게요!!**
- 아래 파일들 생성 및 수정
```
src/main/webapp/WEB-INF/views/admin/register.jsp
src/main/webapp/resources/css2/screens/admin/register.css
src/main/webapp/resources/css2/style.css
src/main/webapp/resources/js/admin/register.js
```
=> feat: [관리자] 회원가입 등록 폼 HTML & CSS & JS

src/main/java/com/universestay/project/user/controller/JoinController.java, src/main/java/com/universestay/project/user/dao/UserJoinDao.java, src/main/java/com/universestay/project/user/dao/UserJoinDaoImpl.java, src/main/java/com/universestay/project/user/service/JoinService.java, src/main/java/com/universestay/project/user/service/JoinServiceImpl.java, src/main/resources/mybatis/mapper/user/UserJoinMapper.xml, src/main/webapp/WEB-INF/views/user/join.jsp, src/main/webapp/resources/js/join.js
=> feat: 회원가입 API - 이메일 중복확인

src/main/java/com/universestay/project/admin/controller/NoticeController.java, src/main/java/com/universestay/project/admin/dao/NoticeDao.java, src/main/java/com/universestay/project/admin/dao/NoticeDaoImpl.java, src/main/java/com/universestay/project/admin/dto/NoticeDto.java, src/main/java/com/universestay/project/admin/dto/NoticePageHandler.java, src/main/java/com/universestay/project/admin/service/NoticeService.java, src/main/java/com/universestay/project/admin/service/NoticeServiceImpl.java, src/main/resources/mybatis/mapper/admin/noticeMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/views/admin/noticeList.jsp, src/main/webapp/WEB-INF/views/admin/noticeList2.jsp, src/main/webapp/WEB-INF/views/admin/noticeWrite.jsp, src/main/webapp/resources/css2/screens/admin/notice_media.css, src/main/webapp/resources/css2/screens/admin/notice_style.css, src/main/webapp/resources/css2/style.css, src/test/java/com/universestay/project/notice/controller/NoticeControllerTest.java, src/test/java/com/universestay/project/notice/dao/NoticeDaoImplTest.java, src/test/java/com/universestay/project/notice/service/NoticeServiceImplTest.java
- 디렉토리 구조 변경으로 원격에서 pull 받으려고 merge 합니다.
=> Task 130 - 관리자 공지사항 화면 구현

src/main/java/com/universestay/project/admin/controller/DashBoardController.java, src/main/java/com/universestay/project/admin/controller/LoginController.java, src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java, src/main/java/com/universestay/project/admin/service/DashBoardService.java, src/main/java/com/universestay/project/admin/service/DashBoardServiceImpl.java, src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml, src/main/webapp/WEB-INF/views/admin/dashboard.jsp, src/main/webapp/resources/css2/screens/admin/dashboard.css, src/main/webapp/resources/css2/style.css, src/main/webapp/resources/js/admin/dashBoard.js
- 관리자 대시보드 구현 완료
- 문의사항 대시보드 '보러가기' 매핑 정보 수정 작업 필요
- refactor: 관리자 로그인 후 redirect로 dashboard로 가도록 수정
- comment: style.css - 관리자 공지사항 css 주석 처리
```
src/main/java/com/universestay/project/admin/controller/DashBoardController.java
src/main/java/com/universestay/project/admin/dao/DashBoardDao.java
src/main/java/com/universestay/project/admin/dao/DashBoardDaoImpl.java
src/main/java/com/universestay/project/admin/service/DashBoardService.java
src/main/java/com/universestay/project/admin/service/DashBoardServiceImpl.java
src/main/resources/mybatis/mapper/admin/dashBoardMapper.xml
src/main/webapp/WEB-INF/views/admin/dashboard.jsp
src/main/webapp/resources/css2/screens/admin/dashboard.css
src/main/webapp/resources/js/admin/dashBoard.js
```
=> feat: 관리자 대시보드 구현 완료

src/main/webapp/WEB-INF/views/admin/eventInput.jsp, src/main/webapp/WEB-INF/views/admin/eventList.jsp, src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp, src/main/webapp/resources/css2/screens/admin/event.css
- eventInput.jsp 이미지 미리보기 추가
- eventInput.jsp 파일첨부 CSS / JS 추가
- event.css 변경(파일 내 style 이동 & BEM 변경)
=> refactor: 관리자 이벤트 입력 페이지 CSS 변경

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/java/com/universestay/project/user/controller/UserLogoutController.java, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/resources/css2/screens/user/main.css, src/main/webapp/resources/js/main/main.js
- 메인화면 숙소 전체 조회 기능 ( 무한스크롤, 랜덤 조회는 추후 구현)
- 숙소 상세로 이동하는 기능 추가
- 코드 변경으로 인한 각종 버그 수정
- main css 수정
- [style: main.css 숙소 wrapping div 사이즈 변경](https://github.com/GeumZzoks/universeStay/commit/347008286c9f5e892103770b1b444fd9bc1d5fd5)
- [feat: 메인화면에 숙소 뿌려주고 roomId를 통해 숙소 상세로 이동하는 기능 추가](https://github.com/GeumZzoks/universeStay/commit/87eaf9400a342fc02d2f578d9123cd5f33190933)
- [fit: 코드 변경으로 인한 userLogin, Logout 컨트롤러 반환값 변경](https://github.com/GeumZzoks/universeStay/commit/1c42e9ecceff5c3c91db2bbcf1b24e2bf0aac1b0)
=> Task 376 : 메인화면 숙소 전체 조회 + 숙소 상세로 이동 기능

src/main/webapp/WEB-INF/views/admin/coupon.jsp, src/main/webapp/resources/css2/screens/admin/coupon.css, src/main/webapp/resources/css2/style.css
- 관리자 쿠폰 페이지 CSS 추가(coupon.css)
- css style 변경(coupon.css 경로 추가)
=> Task 185: 관리자 쿠폰 페이지 CSS 추가

src/main/java/com/universestay/project/user/service/JoinServiceImpl.java, src/main/java/com/universestay/project/user/service/PasswordEncryption.java, src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java, src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java
- 업무에 대한 설명
- 로그인, 회원수정 - 비밀번호 암호화
- 로그인 비밀번호 암호화 메서드 override
- 회원가입 비밀번호 암호화 메서드 override
=> Task 380 - 로그인, 회원수정 - 비밀번호 암호화

src/main/java/com/universestay/project/dto/BookingDto.java
- DB Booking 테이블 is_user_review 컬럼추가로 인한 BookingDto에 is_user_review 인스턴스 변수 추가
- [Refactor: BookingDto에 is_user_review 컬럼 추가](https://github.com/GeumZzoks/universeStay/commit/9137778a74563054db62dad9ef6605856aef68ca)
=> Task 406 : BookingDto에 is_user_review 인스턴스 변수 추가

src/main/webapp/WEB-INF/views/common/user/header.jsp, src/main/webapp/WEB-INF/views/common/user/nav.jsp, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/resources/css2/components/user/header.css, src/main/webapp/resources/css2/components/user/nav.css, src/main/webapp/resources/css2/screens/user/main.css, src/main/webapp/resources/js/user/common/header.js
- 메인화면 캘린더 개선
- 사진 슬라이더 기능 추가
- 각종 버그 및 디자인 수정
- [feat: 숙소 사진에 slider 기능 적용](https://github.com/GeumZzoks/universeStay/commit/3f6af733d0941061cb34300a47fbc0e8d21af9e4)
- [fix: nav바 div 조정](https://github.com/GeumZzoks/universeStay/commit/ebab78b7015068203965fc1f1b9dde409b3054ca)
- [feat & fix: 마이프로필 드롭다운 메뉴 추가 + 각종 버그 수정](https://github.com/GeumZzoks/universeStay/commit/9b18a70a141b7c7d179d1245f150bcd203e3178b)
- [fix & style: 달력 형식 및 디자인 변경](https://github.com/GeumZzoks/universeStay/commit/a5b9b3caaad8c9cfa64a052b19f9d893de1d7b65)
- [fix & style: 달력 형식 및 버그 수정](https://github.com/GeumZzoks/universeStay/commit/c2845ad081e219a824bd5ba29942309286d4a957)
- [fix: 예산 디폴트 값 추가](https://github.com/GeumZzoks/universeStay/commit/60f2c93c70bd5ef7ccc4d4ea2e700c6270249b79)
=> Task 408 : 메인화면 캘린더 개선 & 사진 슬라이더 추가 & 각종 버그 및 디자인 개선

src/main/java/com/universestay/project/room/controller/RoomController.java, src/main/resources/mybatis/mapper/room/roomMapper.xml
- roomMapper.xml 중복 아이디 수정
- roomMapper.xml 중복 아이디 수정
=> refactor: roomMapper.xml 수정

src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/java/com/universestay/project/user/service/UserLoginServiceImpl.java, src/main/webapp/WEB-INF/views/user/loginForm.jsp
- 로그인 에러 수정
- 로그인 에러 발생에 대한 코드 수정
- 로그인 예외 처리 코드 추가
- 주석 정리
=> fix&feat: 로그인 에러 수정 및 예외 처리 추가

src/main/java/com/universestay/project/filter/AdminFilter.java, src/main/java/com/universestay/project/filter/UserFilter.java, src/main/java/com/universestay/project/room/controller/MyBookingController.java, src/main/java/com/universestay/project/room/dao/MyBookingDao.java, src/main/java/com/universestay/project/room/dao/MyBookingDaoImpl.java, src/main/java/com/universestay/project/room/service/MyBookingService.java, src/main/java/com/universestay/project/room/service/MyBookingServiceImpl.java, src/main/resources/mybatis/mapper/room/myBookingMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/views/room/myBookings.jsp
- [] 리뷰작성 구현중
- 리뷰작성은 현재 구현중입니다.
- 일단 성우님이 제 코드 필요로 해서 구현된 부분만 먼저 올릴게요.
=> Feat: Task 117 나의 예약내역 조회 구현

src/main/webapp/WEB-INF/views/room/roomDetail.jsp
- 업무에 대한 설명
- 숙소 상세 페이지 카카오톡 공유 기능
=> Task 417 - 숙소 카카오톡 공유하기

src/main/java/com/universestay/project/room/controller/RoomController.java, src/main/java/com/universestay/project/room/dao/RoomDao.java, src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java, src/main/java/com/universestay/project/room/service/RoomService.java, src/main/java/com/universestay/project/room/service/RoomServiceImpl.java, src/main/resources/mybatis/mapper/room/roomMapper.xml, src/main/webapp/WEB-INF/views/room/roomDetail.jsp, src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp, src/main/webapp/resources/css2/screens/user/main.css, src/main/webapp/resources/css2/screens/user/wishlist.css
=> Refactor: 유저 위시리스트 JSP & CSS 수정

src/main/java/com/universestay/project/room/controller/RoomController.java, src/main/java/com/universestay/project/room/dao/RoomDao.java, src/main/java/com/universestay/project/room/dao/RoomDaoImpl.java, src/main/java/com/universestay/project/room/service/RoomService.java, src/main/java/com/universestay/project/room/service/RoomServiceImpl.java, src/main/resources/mybatis/mapper/room/roomMapper.xml, src/main/webapp/WEB-INF/views/room/roomDetail.jsp, src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp, src/main/webapp/resources/css2/screens/user/main.css, src/main/webapp/resources/css2/screens/user/wishlist.css
- 숙소 자세히 보기 찜하기 & 찜 여부 추가
- RoomMapper 수정
- RoomController 수정
- RoomDao & DaoImpl 수정
- RoomService & RoomServiceImpl 수정
- RoomDetail.jsp 수정 (html & js 추가)
- RoomMapper select 단일 선택 부분에 WishList 조인하고 나머지는 user_id 매개변수 추가해줬습니다.
=> Task 323 : 숙소 상세보기 찜 여부 확인 & 찜하기 기능 추가 / Room Mapper 등 수정

src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/WEB-INF/views/room/roomDetail.jsp, src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp, src/main/webapp/resources/css2/screens/user/wishlist.css
- 위시리스트 추가 & 삭제 modal div 추가(main.jsp & wishList.jsp)
- 위시리스트 추가 or 삭제시 modal js 추가(main.jsp & wishList.jsp)
- 위시리스트 css 수정 (wishlist.css)
=> Task 420: 위시리스트 알림 팝업 모달 추가

src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/WEB-INF/views/room/roomDetail.jsp, src/main/webapp/WEB-INF/views/user/myPage/wishList.jsp, src/main/webapp/resources/css2/screens/user/wishlist.css
- 숙소 개별 페이지에 위시리스트 모달 div & js 추가
- 위시리스트 JSP & CSS 수정
=> Refactor: 위시리스트 CSS 수정 & 숙소 상세보기 모달 추가

src/main/java/com/universestay/project/user/controller/WishListController.java, src/main/webapp/WEB-INF/views/main/main.jsp
- main.jsp js wishList 수정
- main.jsp js getPage 수정
- 아직 메인페이지에서 찜하기가 온전하게 작동하지 않습니다... 조만간 수정하겠습니다.
=> Refactor: 찜하기 & 찜하기 모달 무한스크롤 적용(보완필요)

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/java/com/universestay/project/room/controller/RoomController.java, src/main/java/com/universestay/project/room/dao/RoomDao.java, src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/webapp/WEB-INF/views/room/management.jsp
- 메인 컨트롤러 사용을 위한 일부 리턴 경로 수정
- 
- 메인 컨트롤러 사용을 위한 로그인 컨트롤러 및 룸 컨트롤러 내 일부 리턴 경로 수정
=> refactor: 메인 컨트롤러 사용을 위한 일부 리턴 경로 수정

src/main/java/com/universestay/project/filter/UserFilter.java, src/main/java/com/universestay/project/user/controller/MyBookingController.java, src/main/java/com/universestay/project/user/dao/MyBookingDao.java, src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java, src/main/java/com/universestay/project/user/service/MyBookingService.java, src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java, src/test/java/com/universestay/project/review/dao/ReviewDaoTest.java, src/test/java/com/universestay/project/review/service/RoomReviewServiceTest.java
- task-344 머지 중 에러로 긴급 머지
- 에러 났던 부분 수정
```
src/main/java/com/universestay/project/filter/UserFilter.java
src/main/java/com/universestay/project/user/controller/MyBookingController.java
src/main/java/com/universestay/project/user/dao/MyBookingDao.java
src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java
src/main/java/com/universestay/project/user/service/MyBookingService.java
src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java
src/test/java/com/universestay/project/review/dao/ReviewDaoTest.java
```
=> HOTFIX: task-344 머지 중 에러로 긴급 머지

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/webapp/WEB-INF/views/common/user/header.jsp, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/resources/css2/components/user/header.css, src/main/webapp/resources/css2/screens/user/main.css, src/main/webapp/resources/js/user/common/header.js
#Task 423 : 메인 검색창 검색어 유지 기능 추가 & 메인페이지 css 미디어쿼리, 스타일 수정 & 위시리스트 버그 수정
- 메인 검색창 검색어 유지 기능 추가
- 메인페이지 css 미디어쿼리, 스타일 수정 
- 위시리스트 버그 수정
=> Task 423 : 메인 검색창 검색어 유지 기능 추가 & 메인페이지 css 미디어쿼리, 스타일 수정 & 위시리스트 버그 수정

src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/java/com/universestay/project/admin/controller/LoginController.java, src/main/java/com/universestay/project/admin/dao/EventDao.java, src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java, src/main/java/com/universestay/project/admin/dto/EventImgDto.java, src/main/java/com/universestay/project/admin/service/EventService.java, src/main/java/com/universestay/project/admin/service/EventServiceImpl.java, src/main/resources/mybatis/mapper/admin/EventMapper.xml, src/main/webapp/WEB-INF/views/admin/dashboard.jsp, src/main/webapp/WEB-INF/views/admin/event.jsp, src/main/webapp/WEB-INF/views/admin/eventInput.jsp, src/main/webapp/WEB-INF/views/admin/eventUpdate.jsp, src/main/webapp/WEB-INF/views/common/admin/header.jsp, src/main/webapp/WEB-INF/views/common/admin/navigation.jsp, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/resources/css2/components/admin/header.css, src/main/webapp/resources/css2/screens/admin/coupon.css, src/main/webapp/resources/css2/screens/admin/dashboard.css, src/main/webapp/resources/css2/screens/admin/event.css
- 관리자 페이지 dashboard.jsp 수정
- 관리자 페이지 dashboard.css 수정
- 관리자 header.jsp 수정(기능 추가)
- 관리자 header.css 수정
- 관리자 navigation.jsp 수정(경로 추가)
- 관리자 이벤트 페이지 이미지 업로드 기능 추가
- 관리자 이벤트 페이지 이미지 수정 기능 추가
=> Refactor: 관리자 페이지 JSP & CSS 일괄 수정 & 관리자 이벤트 페이지 이미지 기능 추가

src/main/java/com/universestay/project/user/controller/MyBookingController.java, src/main/webapp/resources/js/room/bookingShare.js
- 나의 예약 페이지(숙소) 경로 수정 @simplist119 확인부탁드립니당!
- 숙소 예약 후, 숙소 예약 내역 공유 페이지(메일 전송)에서 건너뛰기 버튼 URL 경로 수정
=> refactor: 숙소 나의 예약 페이지 경로 수정(경민), 건너뛰기 버튼 수정

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/java/com/universestay/project/main/controller/MainEventController.java, src/main/resources/mybatis/mapper/admin/EventMapper.xml, src/main/webapp/WEB-INF/views/main/eventDetail.jsp, src/main/webapp/WEB-INF/views/main/eventPage.jsp
- 메인 이벤트 페이지 Controller 이동
- (MainController -> MainEventController 생성)
- 이벤트 세부사항 JSP 생성
- (eventDetail.jsp 생성)
- 메인 이벤트 페이지 세부 CSS 수정
- (CSS 분리예정)
=> Refactor : 메인 이벤트 페이지 CSS 수정 / Controller 변경 / 이벤트 세부 페이지 JSP & CSS 추가

src/main/resources/mybatis/mapper/room/roomMapper.xml, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/resources/css2/screens/user/main.css
- 메인화면 CSS 변경 (flex > Grid) 
- 무한스크롤 이슈 수정
- roomapper 수정
=> Task 434 : 메인화면 CSS 변경 (flex > Grid)  & 무한스크롤 이슈 수정 & roomapper 수정

src/main/java/com/universestay/project/payment/controller/PaymentController.java, src/main/java/com/universestay/project/payment/dao/PaymentDao.java, src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java, src/main/java/com/universestay/project/payment/service/PaymentService.java, src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java, src/main/resources/mybatis/mapper/payment/paymentMapper.xml, src/main/webapp/WEB-INF/views/payment/payment.jsp, src/main/webapp/WEB-INF/views/user/myBookings.jsp
=> feat: [1차 개발 진행중] 결제 API

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/java/com/universestay/project/room/controller/RoomController.java, src/main/java/com/universestay/project/room/dao/BookDaoImpl.java
=> Hotfix: BookingDto 경로 변경

src/main/java/com/universestay/project/chat/controller/ChattingController.java, src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java, src/main/webapp/resources/img/symbol/filter_km.svg, src/main/webapp/resources/img/symbol/x_mark_km.svg
- 업무에 대한 설명
- 충돌 해결 및 이미지 추가
hotfix: 충돌 해결 및 이미지 추가
=> hotfix: 충돌 해결 및 이미지 추가

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/java/com/universestay/project/room/service/BookServiceImpl.java, src/main/java/com/universestay/project/user/controller/MyBookingController.java
- fix: 숙소 예약 API 오류 해결
- refactor: 불필요한 코드 제거
- comment: 불필요한 주석 처리
=> fix: 숙소 예약 API 오류 해결

src/main/webapp/WEB-INF/views/common/user/header.jsp
- [feat: header 햄버거 공지사항 버튼 수정](https://github.com/GeumZzoks/universeStay/commit/023290aebf80208c318ff965048bad4a740f821b)
=> Task-449: header 햄버거 공지사항 버튼 수정

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/java/com/universestay/project/user/controller/UserLoginController.java, src/main/java/com/universestay/project/user/controller/UserLogoutController.java, src/main/webapp/WEB-INF/views/common/user/header.jsp
=> fix: 헤더 유저 프로필 쿠키로 관리하도록 기능 변경

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/java/com/universestay/project/user/dto/BookingDto.java, src/main/resources/mybatis/mapper/room/bookRoomMapper.xml, src/main/webapp/WEB-INF/views/room/book.jsp, src/main/webapp/resources/css2/screens/room/book.css, src/main/webapp/resources/js/room/book.js, src/main/webapp/resources/js/room/roomDetail.js
- 숙소 예약 페이지 JS 추가 및 화면단 변경
- DB - Booking 최종 결제 금액 추가(booking_total_pay_amount)
- 결제 선택 HTML 주석 처리(결제 선택은 '나의 여행' 페이지에서 선택 예정)
=> refactor: DB - Booking 최종 결제 금액 추가(booking_total_pay_amount) / 숙소 예약 페이지 JS 추가 및 화면단 변경

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/webapp/WEB-INF/views/room/bookShare.jsp, src/main/webapp/resources/js/room/book.js
- [숙소 - 예약/결제] 메일 보내기 페이지 화면단 변경
- 하단에 보이는 정보: 숙소 이용 규칙, 안전 및 숙소 변경해야함
- 메일 보내기 기능 구현 필요
- 메일 입력 폼 동적으로 추가 생성하기 필요(JS)
=> refactor: [숙소 - 예약/결제] 메일 보내기 페이지 화면단 변경

src/main/java/com/universestay/project/payment/controller/PaymentController.java, src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/resources/mybatis/mapper/payment/paymentMapper.xml, src/main/webapp/WEB-INF/views/room/bookShare.jsp, src/main/webapp/resources/js/payment/payment.js, src/main/webapp/resources/js/room/book.js
- [숙소 - 예약/결제] 메일 보내기 페이지 화면단 변경
- 하단에 보이는 정보: 숙소 이용 규칙, 안전 및 숙소 변경해야함
- 메일 보내기 기능 구현 필요
- 메일 입력 폼 동적으로 추가 생성하기 필요(JS)
- [나의 여행 내역] 숙소 예약 확정 건에 대한 결제 API 수정
- 카드 결제 API 추가 구현 필요
- 카드 결제 취소(환불) 구현 예정
=> 숙소 예약 확정 건에 대한 결제 API 수정 / 메일 보내기 페이지 화면단 변경

src/main/resources/mybatis/mapper/user/myBookingMapper.xml, src/main/webapp/WEB-INF/views/user/myBookings.jsp, src/main/webapp/resources/css2/screens/user/myBookings.css, src/main/webapp/resources/js/payment/payment.js
- 나의 여행 목록 스타일 변경, 보여주는 정보 추가, 결제 대기 상태만 결제 버튼 보이게 기능 추가.
=> feat: 나의 여행 목록 스타일 변경, 보여주는 정보 추가, 결제 대기 상태만 결제 버튼 보이게 기능 추가.

src/main/resources/mybatis/mapper/user/myBookingMapper.xml, src/main/webapp/WEB-INF/views/common/user/header.jsp, src/main/webapp/WEB-INF/views/user/myBookings.jsp, src/main/webapp/resources/css2/screens/user/myBookings.css, src/main/webapp/resources/js/payment/payment.js
=> Hotfix 1221 : roommanagement로 이동되는 버그 수정

src/main/webapp/WEB-INF/views/main/main.jsp
=> hotfix: 잘못 합병된 메인페이지 코드 수정

src/main/webapp/WEB-INF/views/user/join.jsp
=> hotfix: 괄호수정

src/main/webapp/WEB-INF/views/chatting/contact_host.jsp, src/main/webapp/resources/js/chat/contact_host.js
- 업무에 대한 설명
- 호스트에게 처음 메시지 남기는 페이지에 예약기능 함께 추가
=> feat: 호스트 연락할 때 예약하기 기능 추가

src/main/java/com/universestay/project/user/controller/MyBookingController.java, src/main/webapp/WEB-INF/views/common/user/header.jsp, src/main/webapp/WEB-INF/views/user/myBookings.jsp, src/main/webapp/resources/css2/screens/user/myBookings.css, src/main/webapp/resources/js/user/common/header.js
=> Task 444: 숙소 결제, 취소, 결제 완료 표시 기능 완료

src/main/resources/mybatis/mapper/chat/chatRoomMapper.xml
- 업무에 대한 설명
- 채팅방 목록 최신 날짜 순으로 정렬
- 채팅방 목록 최신 날짜 순으로 정렬
=> feat: 채팅방 목록 최신 날짜 순으로 정렬

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/java/com/universestay/project/room/dto/SendEmailBookInfoDto.java, src/main/java/com/universestay/project/room/service/BookShareMailSendService.java, src/main/webapp/WEB-INF/views/room/book.jsp, src/main/webapp/WEB-INF/views/room/bookShare.jsp, src/main/webapp/resources/js/room/book.js, src/main/webapp/resources/js/room/bookingShare.js
- feat: 숙소 예약 완료 후 메일 보내기 기능 구현 추가
- fix: 숙소 예약 페이지 - 달력에 예약된 날짜 표기안됨
- 숙소 예약 페이지, 숙소 예약 확정 페이지 데이터 동적으로 출력되도록 수정
=> feat: 숙소 예약 완료 후 메일 보내기 기능 구현 추가 / fix: 숙소 예약 페이지 - 달력에 예약된 날짜 표기안됨

src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp, src/main/webapp/WEB-INF/views/chatting/contact_host.jsp, src/main/webapp/resources/js/user/join.js
- 업무에 대한 설명
-  회원가입 주소 찾기하고 누르고 바로 창이 안닫힘 문제 해결
- 메시지를 입력 안하면 전송이 안되게 하기
- 실시간 렌더링 시간 format
=> feat: 버그 수정

src/main/java/com/universestay/project/review/dao/RoomReviewDao.java, src/main/java/com/universestay/project/review/dao/RoomReviewDaoImpl.java, src/main/java/com/universestay/project/review/service/RoomReviewService.java, src/main/java/com/universestay/project/review/service/RoomReviewServiceImpl.java, src/main/java/com/universestay/project/room/controller/RoomController.java
- roomReviewAvg 오류 인한 긴급 수정
- [hotfix: roomReviewAvg 오류 수정](https://github.com/GeumZzoks/universeStay/commit/9296509079ae3249af95815b17ee51b0e611fd66)
=> Task 467 : roomReviewAvg 오류 수정

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/webapp/WEB-INF/views/room/book.jsp, src/main/webapp/resources/css2/screens/room/book.css, src/main/webapp/resources/js/room/book.js, src/main/webapp/resources/js/room/roomDetail.js
- fix: 인원 수 계산 시 요금 정산 정상적으로 되도록 수정 완료
- 인원 수 조정 시 넘버링 오류 해결
- 디자인 변경
=> fix: 인원 수 계산 시 요금 정산 정상적으로 되도록 수정 완료 / 인원 수 조정 시 넘버링 오류 해결 / 디자인 변경

src/main/webapp/resources/js/room/book.js
feat: 숙소 상세페이지 js 수정 - 인원 수 입력창 바깥 눌러도 꺼지는 기능
=> feat: 숙소 상세페이지 js 수정 - 인원 수 입력창 바깥 눌러도 꺼지는 기능

src/main/java/com/universestay/project/chat/controller/ChattingController.java, src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java, src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp, src/main/webapp/WEB-INF/views/chatting/chattingRoomList.jsp
=> feat: 채팅 보완

src/main/java/com/universestay/project/chat/controller/ChattingRoomController.java, src/main/java/com/universestay/project/user/controller/UserLoginController.java
- 업무에 대한 설명
- 호스트 연락하기 할때 로그인 안되어있을 때 로그인창으로 갔다가 다시 이전 페이지로 돌아오게 하기
- 호스트 연락하기 할때 로그인 안되어있을 때 로그인창으로 갔다가 다시 이전 페이지로 돌아오게 하기
=> feat: 호스트 연락하기 할때 로그인 안되어있을 때 로그인창으로 갔다가 다시 이전 페이지로 돌아오게 하기

src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp, src/main/webapp/WEB-INF/views/chatting/chattingRoomList.jsp
- 업무에 대한 설명
- 채팅할 때 전송 버튼을 마우스로 클릭해야만 전송이 됨 → 엔터로도 가능하게 하기
- feat: 채팅할 때 전송 버튼을 마우스로 클릭해야만 전송이 됨 → 엔터로도 가능하게 하기
=> feat: 채팅할 때 전송 버튼을 마우스로 클릭해야만 전송이 됨 → 엔터로도 가능하게 하기

src/main/java/com/universestay/project/admin/service/ChangeBookingStatusJob.java, src/main/java/com/universestay/project/common/config/QuartzConfig.java, src/main/java/com/universestay/project/user/dao/MyBookingDao.java, src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java, src/main/java/com/universestay/project/user/service/MyBookingService.java, src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java, src/main/resources/mybatis/mapper/user/myBookingMapper.xml
- [feat: booking status를 이용 완료로 바꾸어주는 xml, dao, service코드 추가](https://github.com/GeumZzoks/universeStay/commit/8ac48ca4eeeec45943bf2946371ac1cf997dc9e4)
- [feat: ChangeBookingStatusJob 생성 및 QuartzConfig설정](https://github.com/GeumZzoks/universeStay/commit/6a0a48f1ef9ec94632c926747271f9da1820ecd6)
=> Task 474 : 매일 자정 예약건에서 체크아웃 날짜가 지난 예약건들은 이용 완료로 상태 변환시키기

src/main/java/com/universestay/project/admin/controller/CouponController.java, src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/java/com/universestay/project/admin/controller/InquiryController.java, src/main/java/com/universestay/project/admin/controller/NoticeController.java, src/main/java/com/universestay/project/admin/controller/UserManagementController.java, src/main/java/com/universestay/project/admin/dao/EventDaoImpl.java, src/main/java/com/universestay/project/main/controller/MainNoticeController.java, src/main/webapp/WEB-INF/views/common/admin/navigation.jsp
comment: 관리자 페이지 - 호스팅 페이지, 문의 사항 주석 / 불필요한 주석 삭제
=> comment: 관리자 페이지 - 호스팅 페이지, 문의 사항 주석 / 불필요한 주석 삭제

src/main/webapp/WEB-INF/views/admin/userInfo.jsp, src/main/webapp/WEB-INF/views/admin/userList.jsp
=> Refactor: 관리자 유저관리 CSS 수정

src/main/java/com/universestay/project/review/controller/RoomReviewController.java, src/main/java/com/universestay/project/user/controller/WishListController.java, src/main/java/com/universestay/project/user/dao/ProfileImgDaoImpl.java, src/main/webapp/WEB-INF/views/room/book.jsp
design: 숙소 예약 페이지 - 호스트 사진 크기 변경
comment: 불필요한 주석 제거
=> design: 숙소 예약 페이지 - 호스트 사진 크기 변경

src/main/webapp/WEB-INF/views/chatting/chattingMessageList.jsp, src/main/webapp/WEB-INF/views/user/join.jsp, src/main/webapp/resources/js/chat/chat.js, src/main/webapp/resources/js/user/join.js
- 업무에 대한 설명
- 채팅 두번 전송 문제 해결
- 채팅 두번 전송 문제 해결
- 전화번호 '-' 기호 추가 안해도 자동추가
=> feat: 채팅 두번 전송 문제 해결

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/java/com/universestay/project/user/controller/MyBookingController.java, src/main/java/com/universestay/project/user/dao/MyBookingDao.java, src/main/java/com/universestay/project/user/dao/MyBookingDaoImpl.java, src/main/java/com/universestay/project/user/service/MyBookingService.java, src/main/java/com/universestay/project/user/service/MyBookingServiceImpl.java, src/main/java/com/universestay/project/user/service/UserInfoServiceImpl.java, src/main/resources/mybatis/mapper/user/myBookingMapper.xml, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/resources/css2/components/user/footer.css
- 메인 푸터 변경 
- 메인 메인사진 맨 앞에 보이도록 하기 
- 리뷰 작성시 점수 반영되게 하기
- 쓸데없는 출력문 제거
=> Task 479 : 메인 푸터 변경 / 메인 메인사진 맨 앞에 보이도록 하기 / 리뷰 작성시 점수 반영되게 하기

src/main/webapp/resources/js/payment/payment.js
=> refactor: 결제 시 UUID 오류 해결

src/main/java/com/universestay/project/room/controller/BookingRoomController.java
=> refactor: 메일 보내기 주소 변경

src/main/java/com/universestay/project/user/controller/MyBookingController.java, src/main/resources/mybatis/mapper/user/myBookingMapper.xml, src/main/webapp/WEB-INF/views/user/myBookings.jsp
=> feat: myBookings에서 host nickname이 예약자의 nickname으로 뜨는 문제 해결

src/main/java/com/universestay/project/admin/controller/EventController.java, src/main/java/com/universestay/project/admin/service/HostingManagementServiceImpl.java, src/main/java/com/universestay/project/filter/AdminFilter.java, src/main/java/com/universestay/project/main/controller/MainController.java, src/main/java/com/universestay/project/oauth/controller/OauthLoginController.java, src/main/java/com/universestay/project/oauth/service/GoogleLoginService.java, src/main/java/com/universestay/project/room/controller/RoomController.java, src/main/java/com/universestay/project/user/controller/JoinController.java, src/main/java/com/universestay/project/user/dao/UserJoinDaoImpl.java, src/main/resources/mybatis/mapper/room/roomMapper.xml, src/main/resources/mybatis/mapper/user/myBookingMapper.xml, src/test/java/com/universestay/project/DBConnectionTest.java
- 검색 안되는 버그 수정
- 리뷰 별점 절삭해서 DB저장
- System.out.println 제거
=> Task 484 : 검색 안되는 버그 수정, 리뷰 별점 절삭해서 DB저장

src/main/java/com/universestay/project/payment/controller/PaymentController.java, src/main/java/com/universestay/project/payment/dao/PaymentDao.java, src/main/java/com/universestay/project/payment/dao/PaymentDaoImpl.java, src/main/java/com/universestay/project/payment/dto/RefundPayDto.java, src/main/java/com/universestay/project/payment/service/PaymentService.java, src/main/java/com/universestay/project/payment/service/PaymentServiceImpl.java, src/main/java/com/universestay/project/room/dao/BookDao.java, src/main/java/com/universestay/project/room/dao/BookDaoImpl.java, src/main/java/com/universestay/project/room/service/BookService.java, src/main/java/com/universestay/project/room/service/BookServiceImpl.java, src/main/resources/mybatis/mapper/payment/paymentMapper.xml, src/main/resources/mybatis/mapper/room/bookRoomMapper.xml, src/main/webapp/resources/js/payment/payment.js
- feat: 결제 취소/예약 취소 API 구현
- fix: 예약 취소/결제 취소 기능 구현 후, 새롭게 숙소 예약할 때 날짜 선택 에러 수정
=> feat: 결제 취소/예약 취소 API 구현 / fix: 예약 취소/결제 취소 기능 구현 후, 새롭게 숙소 예약할 때 날짜 선택 에러 수정

src/main/java/com/universestay/project/main/controller/MainController.java, src/main/webapp/WEB-INF/views/common/user/header.jsp
fix: header isHost를 session으로 관리하도록 수정
=> fix: header isHost를 session으로 관리하도록 수정

src/main/webapp/resources/js/payment/payment.js
=> refactor: 결제/예약 취소 시 confirm 메소드 추가

src/main/java/com/universestay/project/room/controller/BookingRoomController.java, src/main/webapp/WEB-INF/views/room/book.jsp
- refactor: 숙소 예약 페이지 후기 개수 데이터 가져와서 보여주기
=> refactor: 숙소 예약 페이지 후기 개수 데이터 가져와서 보여주기

src/main/webapp/WEB-INF/views/main/eventDetail.jsp, src/main/webapp/WEB-INF/views/room/bookShare.jsp
=> fix: jquery 두번 임포트해서 캘린더 안되는 오류 수정

src/main/java/com/universestay/project/user/controller/HostBookingManagementController.java, src/main/webapp/WEB-INF/views/user/myPage/hostBookingManagement.jsp
=> Fix: 호스트 예약 관리페이지 (hostheader.jsp) 헤더의 게스트모드로 전환 버튼 안나오는 현상 fix
